### ISSUE TITLE
parsing invalid po-files should produce user friendly errors instead of exception

### ISSUE THREAD

**Issue by KennethNielsen** [pyg3t/pyg3t#10]
When trying to parse an invalid file e.g by passing it to poabc, it causes the parser to raise an PoSyntaxError exception. These should be caught in all command line tools and turned into user friendly error messages.

The command line tools are:
gtcat   (CHANGE NOT YET IMPLEMENTED)
gtcompare   (CHANGE NOT YET IMPLEMENTED)
gtmerge   (CHANGE NOT YET IMPLEMENTED)
poabc   (CHANGE NOT YET IMPLEMENTED)
popatch   (CHANGE NOT YET IMPLEMENTED)
gtcheckargs   (CHANGE NOT YET IMPLEMENTED)
gtgrep   (CHANGE NOT YET IMPLEMENTED)
gtxml   (CHANGE NOT YET IMPLEMENTED)
podiff   (CHANGE NOT YET IMPLEMENTED)
poselect   (CHANGE NOT YET IMPLEMENTED)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-02-26T16:25:30Z
 * owner: k-nielsen81
 * the launchpad url was https://bugs.launchpad.net/bugs/941512

**Comment by KennethNielsen** [comment]
(by k-nielsen81)
@Ask Do you agree with the course of action in the last line above?

**Comment by KennethNielsen** [comment]
(by askhl)
I think we should have better error messages in general, yes.  The only annoying thing is that it will be more difficult to get the actual stack trace out.  Perhaps we should add a --debug parameter to control whether it prints a "nice" error message or a stack trace.

**Comment by KennethNielsen** [comment]
(by k-nielsen81)
Yes, that sounds like a good idea. Let's turn this bug into a checklist/whiteboard for these changes.

**Comment by askhl** [comment]
`askhl@jormungandr:~$ gtcat ~/src/pyg3t/pyg3t/gtcat.py
Bad syntax while parsing
Filename: /home/askhl/src/pyg3t/pyg3t/gtcat.py
Current regex: \s*msgid\s*"(?P<line>.*?)"\s*$
Current line: from __future__ import print_function, unicode_literals
Reason: Current line does not match regex
Representation: u'from __future__ import print_function, unicode_literals\n'

Context:

L1: from __future__ import print_function, unicode_literals
`

**Comment by askhl** [comment]
(finally figured out how to insert code correctly)

**Comment by askhl** [comment]
Anyway now if you run gtcat on gtcat (for example), you get the above.

**Comment by KennethNielsen** [comment]
Looks good.

**Comment by askhl** [comment]
We are now using a decorator to do stuff that affects all the scripts.
