### ISSUE TITLE
Possible clean up actions in gtparse

### ISSUE THREAD

**Issue by KennethNielsen** [pyg3t/pyg3t#28]
While recently reading through the ``gtparse`` I stumbled upon a few things, that I think may be candidates for a clean up:

 1. The "roll our own" textwrapper ``chunkwrap``, comes with a comment stating it was done to maintain compatibility with python 2.5. 2.5 was released nearly 9 years ago (September 19, 2006) and is no longer the highest python version available on any platform that I know of (Even the centos server I sometimes work on, which is based on Red Hat Enterprise Linux Server version 6.7.old) has python 2.6. This should of course be investigated more, but given my understanding of Python version on long term support Linux distributions I should even think it was safe to drop 2.6 as well. **Possible solution: After testing that the built-in method does the same, delete out own version and use builtin**
 2. The catalog class has both a ``obsoletes`` property and a ``obsoletes`` method. Since at attribute lookup time, the instance ``__dict__`` is consulted before the class  ``__dict__`` the method is not actually reachable. And since the obsoletes property is a list, which is in itself iterable, it seems largely redundant (though there may be usecases I haven't thought of). A quick grep also shows that all uses inside pyg3t just accesses the property. **Possible solutions: delete the method or rename it to ``iter_obsoletes``**
 3. Upon first glance, the ``Catalog._catalog`` method seems broken. It tries to instantiate a new ``Catalog`` by giving it 4 arguments, but a catalog only takes 3. The code looks like this:
    ```python
    def _catalog(self, msgs, obsoletes=None):
        cat = Catalog(self.fname, self.encoding, msgs, obsoletes)
        return cat
    ```
    
    and presumably could be fixed by concatenating msgs and obsoletes when instantiating ``Catalog``, like so:
    ```python
    def _catalog(self, msgs, obsoletes=None):
        if obsoletes:
            return Catalog(self.fname, self.encoding, msgs + obsoletes)
        else:
            return Catalog(self.fname, self.encoding, msgs)
    ```
 4. By extension of 3, also ``Catalog.get_translated``, ``Catalog.get_untranslated`` and ``Catalog.get_fuzzy`` will not work.
 5. ``wrap()`` turns the generator returned from ``chunkwrap`` into a list, but wrap() is only ever called in one place, and here the return value is only used to iterate over (which generators are good at), so there seems to be no point.

**Comment by askhl** [comment]
Except 1. and 5., which sound like work, these have been fixed.

**Comment by askhl** [comment]
(Well, 5 is easy but let's not touch it except when fixing 1.)

**Comment by KennethNielsen** [comment]
Agreed, there is no real urgency either.

I will get some unittests set up for gtparse soon. When we have those, with proper test for the code were textwrap is used, then it will be trivial to try and exchange for the standard lib one.

**Comment by askhl** [comment]
These things have all been resolved now.  We will keep our own text wrapper since we need special stuff like ANSI escapes.

**Comment by KennethNielsen** [comment]
Ok. Cool.
