### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by kristho91** [pyg3t/pyg3t#33]
Could you please tag a release, so I can get a proper release from github and not from launchpad - for packaging purposes :)

**Comment by askhl** [comment]
Hi Kris!

Yes, it has been too long.  I will try to get to it very soon!  Your packaging work is highly appreciated.

**Comment by askhl** [comment]
Hi Kris!

Very soon now we will have a new version with a more robust parser (ignoring whitespace more systematically), full Python3 support, more robustness for funny/horrible encodings.

(Of course right now everything is still broken :) )
