### ISSUE TITLE
setup.py has references to launchpad

### ISSUE THREAD

**Issue by josephgbr** [pyg3t/pyg3t#34]
> url='https://launchpad.net/pyg3t',
(...)
> download_url='https://launchpad.net/pyg3t/+download',

I assume `url` should be 'https://github.com/pyg3t/pyg3t' and `download_url` 'https://github.com/pyg3t/pyg3t/releases'

**Comment by askhl** [comment]
Thank you, fixed in 8345c3fd34d007a36039acdc0fd3e693f8f7a8cb
