### ISSUE TITLE
test run improvements

### ISSUE THREAD

**Issue by KennethNielsen** [pyg3t/pyg3t#35]
Before including the tests in the PyPI distribution a few things have to be improved:

 1. Handle the dependencies for the tests softly. We don't want to always depend on pytest and mock, but we also do not want running the tests to raise an import error. So try and import and print human readable error message.
 2. Make the pyg3t.test runable so that one can do python -m pytest.test

**Comment by KennethNielsen** [comment]
Should be fixed with e9bc455a002b8d52ef4672d83b05c7ddf72c3f17

**Comment by askhl** [comment]
Thanks!  (It is pythom -m pyg3t.test to be exact, there was a minor typo above, but the implementation is as it should be)

**Comment by KennethNielsen** [comment]
Ahh yes.

Additional info is that if the tests are run with pytest (i.e. `pytest` or `python -m pytest`) then we are assuming that the people running them are developers, that will install the test modules from requirements-dev.txt, and therefore, if the test modules are missing, they will raise an ImportError

However, if the tests are programically:
```python
from pyg3t.test import run
run()
```
or by executing the sub-package as such `python -m pyg3t.test` then we are assuming users and missing test modules will just result in a printed error and no exception (and also of course no tests run).

**Comment by askhl** [comment]
I will be grateful if you can sort out whatever needs to be sorted out :)

**Comment by KennethNielsen** [comment]
Sorted out?

**Comment by askhl** [comment]
I don't quite understand what the issue is. Is one way to run the tests not
sufficient for all cases? But if something should be done (sorted out) then
I trust whatever solution you recommend.

**Comment by KennethNielsen** [comment]
Ah ok. I think we misunderstood each other a bit. I think this is as it should be and I consider everything that should be .. sorted :)
