### ISSUE TITLE
Distutils deprecated, slated for removal in Python 3.12

### ISSUE THREAD

**Issue by rffontenelle** [pyg3t/pyg3t#38]
When building on Python 3.10, the following message is displayed:

```
/build/pyg3t-git/src/pyg3t/setup.py:6: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
```

**Comment by askhl** [comment]
Thanks for reporting - I completely forgot.  Note that pyg3t has actually moved to gitlab.

To be fixed here: https://gitlab.com/pyg3t/pyg3t/-/merge_requests/3

**Comment by rffontenelle** [comment]
@askhl Oh, I was totally unaware of the move to GitLab. If this repo is not used anymore, consider putting a note regarding GitLab and then make it a read-only repo, or set it as a mirror of GitLab. Thanks for the info

**Comment by rffontenelle** [comment]
Closing as solved in GitLab
