### ISSUE TITLE
gtgrep: Ctrl-c when input is standard in results i python backtrace

### ISSUE THREAD

**Issue by KennethNielsen** [pyg3t/pyg3t#6]
When pressing ctrl-c to terminate gtgrep session where the input is std in I recieve an python backtrace:

^CTraceback (most recent call last):
  File "/usr/bin/gtgrep", line 5, in <module>
    gtgrep.main()
  File "/usr/lib/python2.6/dist-packages/pyg3t/gtgrep.py", line 210, in main
    for entry in matches:
  File "/usr/lib/python2.6/dist-packages/pyg3t/gtgrep.py", line 92, in search_iter
    for entry in entries:
  File "/usr/lib/python2.6/dist-packages/pyg3t/gtparse.py", line 248, in parse
    for lineno, lines in self.read_entrylinesets(input):
  File "/usr/lib/python2.6/dist-packages/pyg3t/gtparse.py", line 240, in read_entrylinesets
    entrylines = list(self.read_entrylines(lineiter))
  File "/usr/lib/python2.6/dist-packages/pyg3t/gtparse.py", line 229, in read_entrylines
    line = input.next()
  File "/usr/lib/python2.6/dist-packages/pyg3t/gtparse.py", line 221, in next
    line = self.input.next()
  File "/usr/lib/python2.6/codecs.py", line 1013, in iterdecode
    for input in iterator:
KeyboardInterrupt

It would be nice if we could catch the ctrl-c and give a meaningful feedback.

This may be true for more programs in pyg3t as well.

Regards Kenneth

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-06-14T09:33:13Z
 * owner: k-nielsen81
 * assignee: askhl
 * the launchpad url was https://bugs.launchpad.net/bugs/593584

**Comment by KennethNielsen** [comment]
(by askhl)
This should apply to all utilities, not just gtgrep.

The best way to implemented is probably as a wrapper around the main() function which catches certain kinds of errors.

Maybe add a utility module that the individual scripts can use?

There are other features which it may make sense to implement in a centralized place, such that they can be used by multiple scripts, for example command-line parameters (e.g. --version, or more specific ones such as --color or output formatting options).

**Comment by KennethNielsen** [comment]
(by k-nielsen81)
Agreed, this should apply to all utilities. It is just more visible in the ones that allow input from stdin, because there you get stuck in a ctrl-c situation every time you try to execute the script and forgets the filename.

I'm in favor of implementing this as a wrapper function from a utility module.

**Comment by KennethNielsen** [comment]
(by askhl)
The canonical way to end a programme which reads from the terminal is Ctrl+D ("end of file"), in which case however it just produces a different stacktrace (and "header not found") :)

Maybe if we make sure to always have sensible error messages in case of bad syntax, we can use parser.error(string(e)) where e is the exception.  We could then have different errors that are subject to this, KeyboardInterrupt, PoSyntaxError and so on, while others are not.  Perhaps a --debug option would be useful to turn all stacktraces on.

**Comment by askhl** [comment]
askhl@jormungandr:~$ gtgrep hello
apress Ctrl+DA
No header found in file <stdin>

**Comment by KennethNielsen** [comment]
Nice
