### ISSUE TITLE
podiff produces empty diffchunks in some casese with differing encodings

### ISSUE THREAD

**Issue by KennethNielsen** [pyg3t/pyg3t#8]
Example from diffing testpofile.da.po (from test suite) with its own recoded version

--- Line 4 (testpofile.utf.da.po) 
 # Dummy po-file for testing purposes
 #
 msgid ""
 msgstr ""
 "Project-Id-Version: GTParse test suite\n"
 "PO-Revision-Date: 2009-04-18 18:06+0200\n"
 "Last-Translator: Ask Hjorth Larsen <email address hidden>\n"
 "Language-Team: Dansk <email address hidden>\n"
 "MIME-Version: 1.0\n"
-"Content-Type: text/plain; charset=iso8859-1\n"
+"Content-Type: text/plain; charset=utf-8\n"
 "Content-Transfer-Encoding: 8bit\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"

--- Line 70 (testpofile.utf.da.po) 

--- Line 93 (testpofile.utf.da.po) 

--- Line 98 (testpofile.utf.da.po) 

--- Line 104 (testpofile.utf.da.po) 

--- Line 122 (testpofile.utf.da.po) 

--- Line 127 (testpofile.utf.da.po) 

 =============================================================================
 Number of messages: 6
 =============================================================================

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-12-15T01:59:23Z
 * owner: askhl
 * assignee: k-nielsen81
 * the launchpad url was https://bugs.launchpad.net/bugs/904553

**Comment by KennethNielsen** [comment]
(by k-nielsen81)
Thanks for reporting this.

Fixed in revisions 94 and 95 by adding re-encoding of the msgstrs and comments before diff check.

**Comment by askhl** [comment]
Now that everything is always unicode, we should never think about encodings except when opening files.
